# https://probot.github.io/apps/settings/
repository:
  name: Jamesking56.uk
  description: My personal website
  homepage: https://www.jamesking56.uk
  topics: bootstrap3, bootstrap, pug
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
